#!/usr/bin/env bash
# Write a Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.

i=0
while [ $i -ne 11 ]
do 
	if [ $count -eq 9 ]
	then	
	echo "Hi"
	else
	echo "Holberton School"
	fi	
	((i++))
done
