#!/usr/bin/env bash
# Display Best School in all lines except for the 4th (bad luck) and 8th (good luck)

i=0
while [ $i -ne 10]
do
	if [ $i -eq 3 ]
	then
		echo "bad luck"
	elif [ $i -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
