#!/usr/bin/env bash
# china 4 japan 9 italy 17

i=1
while [ $i -ne 21 ]
do
    echo $i
    case "$i" in
	4)  echo "bad luck from China"
	    ;;
	9) echo "bad luck from Japan"
	    ;;
	17) echo "bad luck from Italy"
	    ;;
	esac
    ((i++))
done
