#!/usr/bin/env bash
# script that gives you information about the file

if [[ -e "school" ]]
then
	echo "school file exists"
	if [[ -s "school"]]
	then
		echo "school file is not empty"
	fi
	if [[ -e "school" && -f "school" ]]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
