#!/usr/bin/env bash
# Script that display, creates and deletes files

echo "ps" > /var/run/myscript.pid

trap 'echo "I hate the kill command"' SIGTERM

trap 'echo "Y U no love me?!"' SIGINT

trap 'rm /var/run/myscript.pid && exit' SIGQUIT SIGTERM

while :
do
	echo "To infinity and beyond"
done 
