#!/usr/bin/env bash
# managing the process of manage_my_process

if [ "$i" == start ]
then
	./manage_my_process start
	echo "ps" > /var/run/my_process.pid
	echo "manage_my_process started"
elif [ "$i" == stop ]
then
	pkill -f ./manage_my_process
	rm /var/run/my_process.pid
	echo "manage_my_process stopped"	
elif [ "$i" == restart ]
then
	pkill -f ./manage_my_process
	rm /var/run/my_process.pid
	manage_my_process start
	echo "ps" > /var/run/my_process.pid
	echo "manage_my_process restarted"
fi
