#!/usr/bin/env bash
# displays To infinity and beyond indefinitely with a sleep 2 in between each iteration, also "I am invincible!!!" when receiving a SIGTERM signal

trap "I am invincible!!!" SIGTERM
while :
do
	echo "To infinity and beyond"
	sleep 2
done
